apiVersion: v1
appVersion: "1.0"
description: A Helm chart for HMCTS Reform IDAM Web Public
name: idam-web-public
version: 0.2.0
keywords:
- java
- web
- springboot
- idam
- sidam
- idam-web-public
- web-public
