java:
  releaseNameOverride: ${SERVICE_NAME}
  image: ${IMAGE_NAME}
  replicas: 2
  ingressHost: ${SERVICE_FQDN}
  ingressIP: ${INGRESS_IP}
  consulIP: ${CONSUL_LB_IP} 
  environment:
    STRATEGIC_SERVICE_URL: https://idam-api-pr-423.service.core-compute-preview.internal
