java:
  releaseNameOverride: idam-web-public
  image: 'hmctspublic.azurecr.io/idam/web-public:preview'
  replicas: 3
  applicationPort: 8080
  keyVaults:
    "idam":
      resourceGroup: idam
      excludeEnvironmentSuffix: false
      secretRef: "kvcreds"
      secrets:
        - AppInsightsInstrumentationKey
  environment:
    STRATEGIC_SERVICE_URL: https://idam-api.service.core-compute-{{ .Values.global.environment }}.internal
    MANAGEMENT_SECURITY_ENABLED: false
    ENDPOINTS_ENABLED: true
    SSL_VERIFICATION_ENABLED: false
    GA_TRACKING_ID: ''

  cpuRequests: '1000m'
  cpuLimits: '2500m'
  memoryRequests: '1024Mi'
  memoryLimits: '2048Mi'
    
  useInterpodAntiAffinity: false
  
  pdb:
    enabled: true
    maxUnavailable: 50%

  aadIdentity: idam

  postgresql:
    enabled: false