java:
  postgresql:
    enabled: false
  releaseNameOverride: idam-web-public
  image: 'hmctspublic.azurecr.io/idam/web-public:preview'
  ingressHost: "{{ .Chart.Name }}.service.core-compute-{{ .Values.global.environment }}.internal"
  replicas: 3
  applicationPort: 8080
  aadIdentityName: idam
  keyVaults:
    "idam-idam":
      resourceGroup: idam-idam
      excludeEnvironmentSuffix: false
      secretRef: "kvcreds"
      secrets:
        - AppInsightsInstrumentationKey
  environment:
    STRATEGIC_SERVICE_URL: https://idam-api.service.core-compute-{{ .Values.global.environment }}.internal
    MANAGEMENT_SECURITY_ENABLED: false
    ENDPOINTS_ENABLED: true
    SSL_VERIFICATION_ENABLED: true
    GA_TRACKING_ID: ''

  cpuRequests: '1000m'
  cpuLimits: '2500m'
  memoryRequests: '1024Mi'
  memoryLimits: '2048Mi'
    
  devmemoryRequests: '512Mi'
  devcpuRequests: '1000m'
  devmemoryLimits: '1024Mi'
  devcpuLimits: '2500m'